# Generated by Django 3.2.20 on 2023-07-31 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.IntegerField(choices=[(0, 'Chore'), (1, 'Errand'), (2, 'Work')], default=0)),
                ('priority', models.IntegerField(choices=[(0, 'High'), (1, 'Middle'), (2, 'Low')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Progressing'), (2, 'Done')], default=0)),
                ('file', models.FileField(upload_to='media/')),
                ('asigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_asigned_to', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
    ]
