# Generated by Django 3.2.20 on 2023-07-31 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('task', '0002_alter_task_asigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='asigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_asigned_to', to='team.membership'),
        ),
    ]
