# Generated by Django 3.2.20 on 2023-10-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammessage',
            options={'ordering': ['-created_at']},
        ),
    ]
